name: dialog_date_range_picker
description: Shows a full screen modal dialog containing a Material Design date range picker..
version: 0.0.1
homepage: "https://github.com/hengmengsroin/dialog-date-range-picker"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
